# Generated by Django 4.0.5 on 2022-06-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='id',
            field=models.CharField(default='bitcoin', max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
    ]
